name: Publish

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch missing tags
        run: git fetch --tags --prune

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install with Bun
        run: bun install

      - name: Semantic Release and Publish
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
